### ISSUE TITLE
GCC-bridge BytePtr is not assignable to CharPtr

### ISSUE THREAD

**Issue by psolaimani** [bedatadriven/renjin#281] opened 2016-11-22 13:51 UTC
**AffyPLM** package depends on **gcrma** package. **gcrma** fails during build:

```
Caused by: java.lang.IllegalAccessException: no such method: 
		org.renjin.bioconductor.XVector.io_utils__.
				new_input_filexp(SEXP)SEXP/invokeStatic
			at java.lang.invoke.MemberName.
				makeAccessException(MemberName.java:754)
			at java.lang.invoke.MemberName$
				Factory.resolveOrFail(MemberName.java:875)
			at java.lang.invoke.MethodHandles$
				Lookup.resolveOrFail(MethodHandles.java:1133)
			at java.lang.invoke.MethodHandles$
				Lookup.linkMethodHandleConstant(MethodHandles.java:1470)
			at java.lang.invoke.MethodHandleNatives.
				linkMethodHandleConstant(MethodHandleNatives.java:382)
			... 45 more
		Caused by: java.lang.VerifyError: Bad type on operand stack
		Exception Details:
		  Location:
		    org/renjin/bioconductor/XVector/io_utils__.new_filexp
				(Lorg/renjin/sexp/SEXP;Lorg/renjin/gcc/runtime/BytePtr;
				Lorg/renjin/gcc/runtime/BytePtr;I)Lorg/renjin/sexp/SEXP; 
				@149: invokestatic
		  Reason:
		    Type 'org/renjin/gcc/runtime/BytePtr' (current frame, stack[0]) is 
			not assignable to 'org/renjin/gcc/runtime/CharPtr'
		  Current Frame:
		    bci: @149
		    flags: { }
		    locals: { 'org/renjin/sexp/SEXP', 'org/renjin/gcc/runtime/BytePtr', 
				'org/renjin/gcc/runtime/BytePtr', integer, '[B', integer, 
				'[B', integer, top, 'org/renjin/bioconductor/XVector/record$zfile', 
				top, top, top, top, 'org/renjin/sexp/SEXP', top, top, top, 
				top, top, top, '[B', integer, 'org/renjin/sexp/SEXP', top, 
				top, 'org/renjin/gcc/runtime/BytePtr' }
		    stack: { 'org/renjin/gcc/runtime/BytePtr' }
```

**Comment by akbertram** [comment] 2016-11-22 13:54
Duplicate of #276

**Closed by akbertram** 2016-11-22 13:54 UTC
Labels: gcc-bridge
