### ISSUE TITLE
Supports compiling casts between pointers of different types (BytePtr -> CharPtr)

### ISSUE THREAD

**Issue by psolaimani** [bedatadriven/renjin#292] opened 2017-01-19 09:40 UTC
Currently `XVector` import by `DESeq2` is failing due to this not supported cast. This is related to previously resolved [issue #276](https://github.com/bedatadriven/renjin/issues/276)

```
org.renjin.eval.EvalException: Exception initializing compiled GNU R library XVector
	at org.renjin.primitives.packaging.Namespace.importDynamicLibrary(Namespace.java:270)
	at org.renjin.primitives.packaging.Namespace.initImports(Namespace.java:234)
	at org.renjin.primitives.packaging.NamespaceRegistry.tryLoad(NamespaceRegistry.java:214)
	at org.renjin.primitives.packaging.NamespaceRegistry.tryGetNamespace(NamespaceRegistry.java:191)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:153)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:115)
	at org.renjin.primitives.packaging.Namespace.initImports(Namespace.java:183)
	at org.renjin.primitives.packaging.NamespaceRegistry.tryLoad(NamespaceRegistry.java:214)
	at org.renjin.primitives.packaging.NamespaceRegistry.tryGetNamespace(NamespaceRegistry.java:191)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:153)
	at org.renjin.primitives.packaging.NamespaceRegistry.getNamespace(NamespaceRegistry.java:115)
	at org.renjin.primitives.packaging.Packages.library(Packages.java:41)
	at org.renjin.primitives.R$primitive$library.doApply(R$primitive$library.java:73)
	at org.renjin.primitives.R$primitive$library.apply(R$primitive$library.java:34)
	at org.renjin.primitives.special.InternalFunction.apply(InternalFunction.java:45)
	at org.renjin.eval.Context.evaluateCall(Context.java:302)
	at org.renjin.eval.Context.evaluate(Context.java:222)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:38)
	at org.renjin.eval.Context.evaluateCall(Context.java:302)
	at org.renjin.eval.Context.evaluate(Context.java:222)
	at org.renjin.eval.Context.evaluate(Context.java:163)
	at org.renjin.sexp.Closure.doApply(Closure.java:84)
	at org.renjin.eval.ClosureDispatcher.apply(ClosureDispatcher.java:73)
	at org.renjin.eval.ClosureDispatcher.applyClosure(ClosureDispatcher.java:58)
	at org.renjin.sexp.Closure.apply(Closure.java:79)
	at org.renjin.eval.Context.evaluateCall(Context.java:302)
	at org.renjin.eval.Context.evaluate(Context.java:222)
	at org.renjin.eval.Context.evaluate(Context.java:163)
	at org.renjin.packaging.NamespaceBuilder2.loadDepends(NamespaceBuilder2.java:83)
	at org.renjin.packaging.NamespaceBuilder2.compile(NamespaceBuilder2.java:66)
	at org.renjin.packaging.PackageBuilder.compileNamespace(PackageBuilder.java:136)
	at org.renjin.packaging.PackageBuilder.build(PackageBuilder.java:52)
	at org.renjin.maven.GnurBuildMojo.execute(GnurBuildMojo.java:69)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.IncompatibleClassChangeError
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:384)
	at org.renjin.bioconductor.XVector.R_init_XVector__.<clinit>(R_init_XVector.c)
	at org.renjin.bioconductor.XVector.XVector.R_init_XVector(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.renjin.primitives.packaging.Namespace.importDynamicLibrary(Namespace.java:267)
	... 53 more
Caused by: java.lang.IllegalAccessException: no such method: org.renjin.bioconductor.XVector.io_utils__.new_input_filexp(SEXP)SEXP/invokeStatic
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:754)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:875)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1133)
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1470)
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:382)
	... 60 more
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/renjin/bioconductor/XVector/io_utils__.new_filexp(Lorg/renjin/sexp/SEXP;Lorg/renjin/gcc/runtime/BytePtr;Lorg/renjin/gcc/runtime/BytePtr;I)Lorg/renjin/sexp/SEXP; @148: invokestatic
  Reason:
    Type 'org/renjin/gcc/runtime/BytePtr' (current frame, stack[0]) is not assignable to 'org/renjin/gcc/runtime/CharPtr'
  Current Frame:
    bci: @148
    flags: { }
    locals: { 'org/renjin/sexp/SEXP', 'org/renjin/gcc/runtime/BytePtr', 'org/renjin/gcc/runtime/BytePtr', integer, '[B', integer, '[B', integer, top, 'org/renjin/bioconductor/XVector/record$zfile', top, top, top, top, 'org/renjin/sexp/SEXP', top, top, top, top, top, top, '[B', integer, 'org/renjin/sexp/SEXP', top, top, 'org/renjin/gcc/runtime/BytePtr' }
    stack: { 'org/renjin/gcc/runtime/BytePtr' }
  Bytecode:
    0000000: 2bb4 0011 3a04 2bb4 0015 3605 2cb4 0011
    0000010: 3a06 2cb4 0015 3607 bb00 3059 b700 7b3a
    0000020: 092a b800 7f99 0011 a700 032a b800 8304
    0000030: a000 06a7 0017 bb00 0d59 1285 b600 5303
    0000040: b700 1803 bd00 04b8 008b 2a03 b800 593a
    0000050: 0eb2 008e 3a17 190e 1917 a500 06a7 0017
    0000060: bb00 0d59 1290 b600 5303 b700 1803 bd00
    0000070: 04b8 008b 190e b800 933a 1a19 1ab4 0011
    0000080: 3a15 191a b400 1536 16bb 000d 5919 1515
    0000090: 16b7 0018 b800 993a 1b19 1bb4 009e c000
    00000a0: 263a 0a19 1bb4 009f 360b 190e b800 5d3a
    00000b0: 1c19 1cb4 0011 3a13 191c b400 1536 1419
    00000c0: 09bb 000d 5919 1315 14b7 0018 bb00 0d59
    00000d0: 190a 150b b700 18bb 000d 5919 0415 05b7
    00000e0: 0018 bb00 0d59 1906 1507 b700 181d b800
    00000f0: a3b6 00a6 bb00 3059 b700 7b3a 0819 08c6
    0000100: 0006 a700 1c19 09b8 0034 bb00 0d59 12a8
    0000110: b600 5303 b700 1803 bd00 04b8 008b 1908
    0000120: 1909 b600 a6b2 003c 3a12 b200 3c3a 1119
    0000130: 0819 1119 12b8 00ac 3a0d 190d b800 af57
    0000140: bb00 0d59 190a 150b b700 18b8 00b3 3a0c
    0000150: 190c b800 af57 bb00 0d59 12b5 b600 5303
    0000160: b700 18b8 00b8 3a10 190d 1910 190c b800
    0000170: bc57 05b8 00c0 190d b0                 
  Stackmap Table:
    full_frame(@43,{Object[#113],Object[#13],Object[#13],Integer,Object[#38],Integer,Object[#38],Integer,Top,Object[#48]},{})
    same_frame(@54)
    same_frame(@74)
    full_frame(@96,{Object[#113],Object[#13],Object[#13],Integer,Object[#38],Integer,Object[#38],Integer,Top,Object[#48],Top,Top,Top,Top,Object[#113],Top,Top,Top,Top,Top,Top,Top,Top,Object[#113]},{})
    same_frame(@116)
    full_frame(@261,{Object[#113],Object[#13],Object[#13],Integer,Object[#38],Integer,Object[#38],Integer,Object[#48],Object[#48],Object[#38],Integer,Top,Top,Object[#113],Top,Top,Top,Top,Object[#38],Integer,Object[#38],Integer,Object[#113],Top,Top,Object[#13],Object[#155],Object[#13]},{})
    same_frame(@286)

	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:847)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:872)
	... 63 more
WARNING: Failed to import dynLib entries for XVector, expect subsequent failures
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.761s
[INFO] Finished at: Thu Jan 19 10:26:43 CET 2017
[INFO] Final Memory: 30M/1002M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.renjin:renjin-maven-plugin:0.8.2318:gnur-compile (compile) on project SummarizedExperiment: Unknown NAMESPACE directive 'importClassFrom' -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.renjin:renjin-maven-plugin:0.8.2318:gnur-compile (compile) on project SummarizedExperiment: Unknown NAMESPACE directive 'importClassFrom'
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unknown NAMESPACE directive 'importClassFrom'
	at org.renjin.maven.GnurBuildMojo.execute(GnurBuildMojo.java:75)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: org.renjin.eval.EvalException: Unknown NAMESPACE directive 'importClassFrom'
	at org.renjin.primitives.packaging.NamespaceFile.parseCall(NamespaceFile.java:326)
	at org.renjin.primitives.packaging.NamespaceFile.parse(NamespaceFile.java:277)
	at org.renjin.primitives.packaging.NamespaceFile.parse(NamespaceFile.java:266)
	at org.renjin.primitives.packaging.NamespaceFile.parse(NamespaceFile.java:235)
	at org.renjin.packaging.NamespaceBuilder2.importDependencies(NamespaceBuilder2.java:92)
	at org.renjin.packaging.NamespaceBuilder2.compile(NamespaceBuilder2.java:67)
	at org.renjin.packaging.PackageBuilder.compileNamespace(PackageBuilder.java:136)
	at org.renjin.packaging.PackageBuilder.build(PackageBuilder.java:52)
	at org.renjin.maven.GnurBuildMojo.execute(GnurBuildMojo.java:69)
	... 21 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by akbertram** [comment] 2017-02-21 22:28
Duplicate of #276

**Comment by psolaimani** [comment] 2017-03-01 11:30
issue #276 is caused by IntPtr > BytePtr cast while this issue is due to BytePtr > CharPtr cast.

This happens in `new_filexp` function inside  [io_utils.c](https://github.com/Bioconductor-mirror/XVector/blob/release-3.3/src/io_utils.c#L486):
```expath = R_ExpandFileName(translateChar(filepath0));```

**Comment by akbertram** [comment] 2017-03-06 06:15
The C type `char` is actually a single byte, and so should be represented in JVM-land as `byte` / `BytePtr`. This naming mismatch is because Java uses a two-byte UTF-16 encoding of strings as its internal representation, while C initially used single-byte character encoding. Support for multi-byte character encodings was later added to the C standard library, and the type used is `wchar_t` for "wide character".

So the signature of R_ExpandFileName in the Utils class is wrong. Given the C signature of:
 
    const char *R_ExpandFileName(const char *);

    public static BytePtr R_ExpandFileName(BytePtr p0);

It looks like this is my mistake in the [code generator](https://github.com/bedatadriven/renjin/blob/eed6a20c358d763bd585c346ad4c89085b058b31/tools/gnur-installation/generateStubs.groovy#L143-L143), which I seem to have mostly corrected in Rinternals but not in the Utils class.

To fix this, mark the incorrect methods as `@Deprecated` and add a new method with the correct signature. We want to avoid removing the methods as much as possible to avoid `NoSuchMethodError` exceptions thrown by existing code.

**Closed** 2017-03-06 11:15 UTC
Labels: gcc-bridge
