### ISSUE TITLE
Dollar assignment with rhs of type "string"

### ISSUE THREAD

**Issue by krlmlr** [bedatadriven/renjin#302] opened 2017-02-07 09:34 UTC
I've noticed that the assertthat package is unavailable in your repo due to failure to compile R code. Looking at the [build logs](http://packages.renjin.org/package/org.renjin.cran/assertthat/0.1/build/301), I think the code that triggers the failure is of the form `env$"name" <- ...` (see also [assertthat source](https://github.com/hadley/assertthat/blob/e183ccdc515bbb8e7f32d8d16586aed9eea6de0b/R/base-comparison.r#L12-L17)). This is in a renjin shell:

```r
> base <- new.env()
> base$"<=" <- 5
ERROR: Invalid argument:
	$<-(environment, character, double)
	Expected:
	$<-(list, Symbol, any)
	$<-(pairlist, Symbol, any)
	$<-(Environment, Symbol, any)
	$<-(AtomicVector, Symbol, any)
	$<-(ExternalPtr, any, any)
```

This seems to be supported in GNU R, even if slightly unorthodox.

**Comment by mjkallen** [comment] 2017-02-07 09:53
Thanks for reminding us Kirill. This is a duplicate of #138.

**Closed by mjkallen** 2017-02-07 09:53 UTC
