### ISSUE TITLE
Support dplyr and tidyr in Renjin

### ISSUE THREAD

**Issue by fredfeng** [bedatadriven/renjin#333] opened 2017-09-03 22:34 UTC
Dear authors,

I was wondering whether you guys have any plan to support dplyr and tidyr in Renjin?

Thanks,

**Comment by DaveJarvis** [comment] 2017-10-13 04:37
See:

* http://packages.renjin.org/package/org.renjin.cran/dplyr
* http://packages.renjin.org/package/org.renjin.cran/tidyr
* http://packages.renjin.org/package/org.renjin.cran/dplyr/0.7.4/build/1

Here's a thread that may be helpful:

* https://groups.google.com/forum/#!topic/renjin-dev/8LW-3oayxiE

**Comment by akbertram** [comment] 2017-10-23 15:23
There's no reason  that Renjin can't "support" these packages, it's just a question of identifying and fixing the individual bugs in Renjin that keep these packages from building and/or passing tests.

If you can take a look through the build logs and open specific issues affecting these packages than I'm happy to help resolve them. For example, dplyr and tidyr both seem to be blocked by a relatively minor problem compiling the native sources. I've opened issue #340 for this. 

I'm going to close this issue but don't hesitate to open more specific issues related to these packages.

**Closed by akbertram** 2017-10-23 15:23 UTC

**Comment by jdimeo** [comment] 2018-07-12 16:37
Hello @akbertram - 0.7.5 of `dplyr` is now failing due to a missing PostgresSQL dependency (according to the Maven build log), which is a bummer because `dplyr` is very powerful/common even when used in memory (and it doesn't show up as a package dep here: http://packages.renjin.org/package/org.renjin.cran/dplyr/0.7.5)

0.7.6 hasn't been built yet since it was recently released (6/29), but I assume will fail in the same way as 0.7.5. What can I do to help getting the `dplyr` build working?

**Comment by jdimeo** [comment] 2019-05-12 02:44
Hello again @akbertram I'm still really wanting to use Renjin and `dplyr` is still the thorn in my side. Now it looks like 0.8.0 _would_ work, if `rlang` 0.3.4 would get fixed. In fact, `rlang` is blocking `dplyr`, `pillar`, and `tibble` from working- so big bang for the buck to get it working again.

The problem there is:
`Caused by:org.renjin.gcc.runtime.UnsatisfiedLinkException: Function 'R_ParseVector' was not found at compile-time`
per http://packages.renjin.org/package/org.renjin.cran/rlang/0.3.4

I would love to contribute but I don't know where to begin. How can I reproduce the package build locally? I've seen where you've forked `rlang`, but there is no POM in the fork, so I'm not sure where to look for who actually controls these builds. I feel like once I can reproduce the build error myself, I can begin working on a fix.
