### ISSUE TITLE
Graphics support in Renjin 0.9.2716

### ISSUE THREAD

**Issue by perNyfelt** [bedatadriven/renjin#432] opened 2018-12-21 10:07 UTC
According to Alex Bertram: "Mostly this should work in the same way as in GNU R. For example, the following will write a simple plot to disk:

```
    png(filename="plot.png")
    plot(1:12)
    dev.off()
```
"
However, executing this in Renjin Studio on Linux Mint, JDK 1.8 and on Windows 10 JDK 1.8 both gives an error on col2rgb as follows:
```
Renjin 0.9.2716
Copyright (C) 2018 The R Foundation for Statistical Computing
Copyright (C) 2018 BeDataDriven
> png(filename="plot.png")
Error: Exception calling col2rgb : null
> plot(1:12)
Error: Exception calling list(name = devholdflush, address = org.renjin.sexp.ExternalPtr@69bbe08d, numParameters = c(1L)) : null
> dev.off()
Error: Exception calling list(name = devcur, address = org.renjin.sexp.ExternalPtr@6b496f2a, numParameters = c(1L)) : null
> 
```

**Comment by akbertram** [comment] 2018-12-21 10:18
Duplicate of #434

**Closed by akbertram** 2018-12-21 10:18 UTC
